version: "2"
services:
  os_open_mysql:
     image: mysql:5.6
     container_name: os_open_mysql
     volumes:
       - /data/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: os_open_root
       MYSQL_DATABASE: os_open
       MYSQL_USER: os_open_user
       MYSQL_PASSWORD: os_open_pwd

  os_open_redis:
    container_name: os_open_redis
    image: redis:4.0.13
    ports:
      - "16379:6379"
    command: redis-server --requirepass 'redis_pwd'
    volumes:
      - /data/redis:/data
    restart: always

  os_open_emq:
    image: registry.cn-beijing.aliyuncs.com/os-open/emqttd-docker-v2.3.11:latest
    container_name: os_open_emqtt
    hostname: os_open_emqtt
    ports:
      - 11883:1883
      - 18083:8083
      - 18883:8883
      - 18084:8084
      - 11808:1808
    command: /opt/emqttd/start.sh
    restart: always


  os_open_rabbitmq:
    image: rabbitmq:3.7.12
    container_name: os_open_rabbitmq
    hostname: os_open_rabbitmq
    ports:
      - 15672:5672
      - 14369:4369
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  os_open_manage:
    image: registry.cn-beijing.aliyuncs.com/os-open/manage:latest
    container_name: os_open_manage
    hostname: os_open_manage
    ports:
      - 18081:80
    command: bash -c 'bash /tmp/import.sh && /usr/bin/supervisord'
    restart: always
    depends_on:
      - os_open_mysql
      - os_open_emq
      - os_open_redis
      - os_open_rabbitmq
    links:
      - os_open_rabbitmq

  os_open_api:
    image: registry.cn-beijing.aliyuncs.com/os-open/api:latest
    container_name: os_open_api
    hostname: os_open_api
    ports:
      - 18082:80
    depends_on:
      - os_open_mysql
      - os_open_emq
      - os_open_redis
      - os_open_rabbitmq
    links:
      - os_open_rabbitmq
      - os_open_manage
    command: /usr/bin/supervisord
    restart: always

  os_open_console:
    image: registry.cn-beijing.aliyuncs.com/os-open/console:latest
    container_name: os-open-console
    hostname: os-open-console
    ports:
      - 18080:80
    command: /usr/bin/supervisord
    restart: always
    links:
      - os_open_manage
    environment:
      DOMAIN_NAME: